ApiNest/Controllers/ApiRegistrationsController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ApiNest.Domain;
using Microsoft.AspNet.Identity;

namespace ApiNest.Controllers
{

    public class ApiRegistrationsController : Controller
    {
        private IApiNestSession db = new ApiNestContext();

        // GET: ApiRegistrations
        public ActionResult Index()
        {
            return View(db.ApiRegistrations.ToList());
        }

        // GET: ApiRegistrations/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApiRegistration apiRegistration = db.ApiRegistrations.Single(ar => ar.Id == id);
            if (apiRegistration == null)
            {
                return HttpNotFound();
            }
            return View(new ApiRegistrationVm(apiRegistration));
        }

        // GET: ApiRegistrations/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Name,EntryPointUrl")] ApiRegistrationVm postModel)
        {


            if (ModelState.IsValid)
            {
                var userId = HttpContext.User.Identity.GetUserId();
                var currentUser = db.Users.Single(u => u.Id == userId);
                db.AddApiRegistration(postModel.Name, postModel.EntryPointUrl, currentUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(postModel);
        }

        [Authorize]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userId = HttpContext.User.Identity.GetUserId();
            ApiRegistration apiRegistration = db.Users
                .Where(u => u.Id == userId)
                .SelectMany(u => u.OwnedApiRegistrations)
                .Single(x => x.Id == id);
            if (apiRegistration == null)
            {
                return HttpNotFound();
            }
            return View(new ApiRegistrationVm(apiRegistration));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ApiRegistrationVm postModel)
        {
            if (ModelState.IsValid)
            {
                var userId = HttpContext.User.Identity.GetUserId();
                db.Users
                    .Where(u => u.Id == userId)
                    .SelectMany(u => u.OwnedApiRegistrations)
                    .Single(x => x.Id == postModel.Id)
                    .UpdateDetails(postModel.Name, postModel.EntryPointUrl);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(postModel);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class ApiRegistrationVm
        {
            public ApiRegistrationVm()
            {
            }

            public ApiRegistrationVm(ApiRegistration apiRegistration)
            {
                this.Name = apiRegistration.Name;
                this.EntryPointUrl = apiRegistration.EntryPointUrl;
                this.Id = apiRegistration.Id;
            }

            public string Name { get; set; }

            public string EntryPointUrl { get; set; }

            [DataType("Hidden")]
            public string Id { get; set; }
        }

    }
}

ApiNest/Controllers/ProxyRegistrationsController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ApiNest.Domain;
using Microsoft.AspNet.Identity;

namespace ApiNest.Controllers
{
    
    public class ProxyRegistrationsController : Controller
    {
        private IApiNestSession db = new ApiNestContext();

        // GET: ProxyRegistrations
        public ActionResult Index()
        {
            return View(db.ProxyRegistrations.ToList());
        }

        // GET: ProxyRegistrations/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProxyRegistration proxyRegistration = db.ProxyRegistrations.Single(x => x.Id == id);
            if (proxyRegistration == null)
            {
                return HttpNotFound();
            }
            return View(new ProxyRegistrationVm(proxyRegistration));
        }

        // GET: ProxyRegistrations/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Name,EntryPointUrl")] ProxyRegistrationVm proxyRegistration)
        {
            if (ModelState.IsValid)
            {
                var userId = HttpContext.User.Identity.GetUserId();
                var applicationUser = db.Users.Single(u => u.Id == userId);
                db.AddProxyRegistration(proxyRegistration.Name, proxyRegistration.EntryPointUrl, applicationUser);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(proxyRegistration);
        }

        [Authorize]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userId = HttpContext.User.Identity.GetUserId();
            var proxyRegistration = db.Users
                .Where(u => u.Id == userId)
                .SelectMany(u => u.OwnedProxyRegistrations)
                .Single(x => x.Id == id);
            if (proxyRegistration == null)
            {
                return HttpNotFound();
            }
            return View(new ProxyRegistrationVm(proxyRegistration));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,EntryPointUrl")] ProxyRegistrationVm postModel)
        {
            if (ModelState.IsValid)
            {
                var userId = HttpContext.User.Identity.GetUserId();
                var proxyRegistration = db.Users
                    .Where(u => u.Id == userId)
                    .SelectMany(u => u.OwnedProxyRegistrations)
                    .Single(x => x.Id == postModel.Id);
                proxyRegistration.UpdateDetails(postModel.Name, postModel.EntryPointUrl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(postModel);
        }

        
 

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class ProxyRegistrationVm
        {
            public ProxyRegistrationVm() { }
            public ProxyRegistrationVm(ProxyRegistration proxyRegistration)
            {
                this.Name = proxyRegistration.Name;
                this.EntryPointUrl = proxyRegistration.EntryPointUrl;
                this.Id = proxyRegistration.Id;
            }

            public string Name { get; set; }

            public string EntryPointUrl { get; set; }

            [DataType("Hidden")]
            public string Id { get; set; }
        }
    }
}

ApiNest/Views/Shared/_Layout.cshtml
@using ApiNest.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="/Content/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />

 
    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace","Ajax"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"24fe54be-55ff-4ccc-8486-3b0afa2e3e2e"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ApiNest", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Mashups", "Index", "Mashups")</li>
                    <li>@Html.ActionLink("Proxy Registrations", "Index", "ProxyRegistrations")</li>
                    <li>@Html.ActionLink("Api Registrations", "Index", "ApiRegistrations")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="/Scripts/jquery-migrate-1.1.0.min.js" type="text/javascript"></script>
    <script src="/Scripts/bootstrap3-typeahead.js" type="text/javascript"></script>
    <script src="/Scripts/bootstrap3-typeahead.unobtrusive.js" type="text/javascript"></script>
    <script src="/Scripts/jquery-ui-1.8.ackage 23.min.js" type="text/javascript"></script>
    <script src="/Scripts/jquery.validate.js" type="text/javascript"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.dynamic.js" type="text/javascript"></script>

    <script src="/bower_components/jqueryui-timepicker-addon/dist/jquery-ui-sliderAccess.js"></script>
    <script src="/bower_components/jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.js"></script>
    <script src="/bower_components/jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.min.js"></script>
    <link href="/bower_components/jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.css" rel="stylesheet" />
    <link href="/bower_components/jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.min.css" rel="stylesheet" />

    <link href="/Content/FormFactory/FormFactory.css" rel="stylesheet" type="text/css" />
    <script src="/Scripts/FormFactory/FormFactory.js" type="text/javascript"></script>
    <script src="/Scripts/Prettify/prettify.js"></script>
    <link href="/Content/Prettify/prettify.css" type="text/css" rel="stylesheet" />
    @RenderSection("scripts", required: false)
</body>
</html>